---
title: "Work with Me"
subtitle: "Consulting, Development & Teaching"
comments: false
format: 
  html: 
    theme: 
      light: [cosmo, theming.scss]
      dark: [darkly, theming.scss]
---

---

## Consultation Firm

:::: {.info-grid}

::: info-card

### What I Offer

***Mathematics & statistics foundation***

-   Calculus
-   Linear Algebra
-   Probability and statistics theory

***Statistical modelling & Machine Learning 1***

-   Statistical inference and simulation
-   Bayesian inference with Stan/CmdStan
-   Custom model development and validation

***Statistical modelling & Machine Learning 2***

-   Experimental design and causal inference
-   Longitudinal study and time series analysis & forecasting
-   Applications with Python and R

### Research & Methods Consultation

-   **Study design** and methodology review
-   **Statistical analysis** plan development
-   **Longitudinal studies** and panel data
-   **Power analysis** and sample size calculation
-   **Manuscript review** (methods & results sections)

:::

::: info-card

### What I Offer

***Data Science***

-   Data Visualization (`{ggplot2}`, `{altair}`)
-   Shiny app development
-   Data manipulation and relational algebra with SQL and `{tidyverse}`
-   Geospatial data analysis

***Package Development***

-   R/Python package development
-   API design and documentation
-   Testing frameworks
-   Open-source maintenance strategies

:::

<!-- 4.  Code Review & Optimization -->

<!--     -   Architecture review of existing projects -->
<!--     -   Performance audits and refactoring -->
<!--     -   Best practices implementation -->

### Rates, Inquiry & Engagement

::: info-card

-   **Retainer packages available** for ongoing work
-   [Book the consultation firm in Calendly](https://calendly.com/joshua-marie-k/consulting-firm)
-   Or email me at: [joshua.marie.k@gmail.com](joshua.marie.k@gmail.com)

:::

::::

## Course Tutorial

This is a live session with me, prepared with interactive slides. 

### Available Now

[Core of R Programming](https://calendly.com/joshua-marie-k/course-tutorial-1)

-   Course section 1: Functional programming
-   Course section 2: Performance optimization
-   Course section 3: Metaprogramming

### Coming Soon

<!-- **Core of Python Programming** -->
<!-- -  Python internals and data model -->
<!-- -  High-performance numerical computing -->
<!-- -  Building C/Rust extensions -->

**Bayesian Inference with Stan**
-   Course section 1: Probabilistic programming fundamentals
-   Course section 2: Stan mechanics
-   Course section 3: Model building and diagnostics

## Products

### Not available for now
